
			myboard.move('White', Pawn ,'e4')
			myboard.move('Black', Pawn,'e5')
			myboard.move('White',Bishop,'c4')
			myboard.move('Black', Queen,'g5')
			myboard.move('White',Knight,'f3')
			myboard.move('Black', Queen,'g6')
			myboard.move('White',Knight,'e5')
		
			myboard.move('Black', Knight,'c6')
			myboard.move('White',Knight,'g6')
			myboard.move('Black', Pawn,'b5')
			myboard.move('White',Knight,'h8')
			myboard.move('Black', Bishop,'b7')
			myboard.move('White',Knight,'f7')
			myboard.move('Black', Knight,'d8')
			myboard.move('White',Knight,'h6')
			myboard.move('Black', King,'e7')